const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..');
(async()=>{let browser,server;try{
let url=process.env.LMS_TEST_URL;
if(!url){server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;}
let args=[];if(process.env.CHROMIUM_BUNDLE){const bundle=(await import(process.env.CHROMIUM_BUNDLE)).default;args=bundle.args;}browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForSelector('#lms-heading');const course=await page.evaluate(()=>window.NEXT_LMS_COURSE),walk=ns=>ns.flatMap(n=>n.type==='section'?walk(n.children):[n]);const nodes=walk(course.sections),decks=nodes.filter(n=>n.type==='slides');
for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page overflow at '+width);const b=page.locator('[data-lms="outline"]');await b.click();assert.equal(await b.getAttribute('aria-expanded'),'false');await b.click();assert.equal(await b.getAttribute('aria-expanded'),'true');assert.ok(await page.locator('#lms-outline-search').isVisible());}
const search=page.locator('#lms-outline-search');await search.fill('getServerSideProps');assert.ok((await page.locator('#lms-search-count').textContent()).includes('matching'));assert.ok(await page.locator('#lms-outline button[data-id]').count()>0);await search.fill('unmatchable-learning-test-xyz');assert.equal(await page.locator('#lms-outline button[data-id]').count(),0);await search.fill('');
// Test source code rendering and the heading/code distinction.
const queryDeck=decks.find(n=>n.slides.some(s=>s.body.includes('```tsx')&&s.body.includes('filename=')));await search.fill(queryDeck.title);await page.locator(`[data-id="${queryDeck.id}"]`).click();const codeSlide=queryDeck.slides.findIndex(s=>s.body.includes('```tsx')&&s.body.includes('filename='));for(let i=0;i<codeSlide;i++)await page.locator('[data-lms="slide-next"]').click();assert.ok(await page.locator('.lms-prose pre code').count()>0);assert.ok((await page.locator('.lms-prose').textContent()).includes('.tsx'));await page.locator('#lms-outline-search').fill('');
const safe=await page.evaluate(()=>{const t=document.createElement('div');t.innerHTML=LMSMarkdown('[bad](javascript:alert(1))\n\n<img src=x onerror=alert(1)>\n\n<script>alert(1)</script>\n\n```tsx\n<script>alert(2)</script>\n```');return {unsafe:!!t.querySelector('script,[onerror],a[href^="javascript:"]'),code:t.querySelector('pre code').textContent};});assert.equal(safe.unsafe,false);assert.ok(safe.code.includes('<script>'));
// Render every slide with the same browser DOM renderer used by lessons.
const slides=decks.flatMap(n=>n.slides);for(let offset=0;offset<slides.length;offset+=200){await page.evaluate(batch=>{for(const s of batch){const t=document.createElement('div');t.innerHTML=LMSMarkdown(s.body);if(!t.textContent.trim())throw Error('Empty slide '+s.id);if(t.querySelector('script,[onerror],a[href^="javascript:"]'))throw Error('Unsafe slide '+s.id);}},slides.slice(offset,offset+200));if(offset%1000===0)console.log('Rendered',Math.min(offset+200,slides.length),'/',slides.length);}
// Notes and completion survive reload.
const welcome=decks[0];await page.locator(`[data-id="${welcome.id}"]`).click();assert.ok(await page.locator('[data-lms="complete"]').isDisabled());await page.locator('[data-lms-notes]').fill('My study note');for(let i=1;i<welcome.slides.length;i++)await page.locator('[data-lms="slide-next"]').click();await page.locator('[data-lms="complete"]').click();await page.reload();assert.ok((await page.locator(`[data-id="${welcome.id}"]`).textContent()).includes('Complete'));assert.equal(await page.locator('[data-lms-notes]').inputValue(),'My study note');
const quiz=nodes.find(n=>n.type==='quiz');await page.locator('#lms-outline-search').fill(quiz.title);await page.locator(`[data-id="${quiz.id}"]`).click();for(const q of quiz.questions)await page.locator(`input[name="q-${q.id}"][value="${q.answer}"]`).check();await page.locator('#lms-quiz button[type="submit"]').click();assert.ok((await page.locator('.lms-result').allTextContents()).join(' ').includes('100%'));await page.locator('#lms-outline-search').fill('');
await page.locator('[data-lms="view"][data-view="report"]').click();assert.ok((await page.locator('#lms-main').textContent()).includes(quiz.skill));await page.locator('[data-lms="view"][data-view="settings"]').click();await page.locator('#lms-unlock-all').uncheck();await page.locator('[data-lms="view"][data-view="learn"]').click();assert.ok(await page.locator(`[data-id="${course.finalQuiz.id}"]`).isDisabled());
// Verify independent main scrolling on a long documentation section.
const long=decks.find(n=>n.slides.some(s=>s.body.length>10000));await page.locator('#lms-outline-search').fill(long.title);await page.locator(`[data-id="${long.id}"]`).click();const idx=long.slides.findIndex(s=>s.body.length>10000);for(let i=0;i<idx;i++)await page.locator('[data-lms="slide-next"]').click();assert.ok(await page.evaluate(()=>{const m=document.querySelector('#lms-main');m.scrollTop=200;return m.scrollTop>0&&document.documentElement.scrollTop===0;}));
await page.locator('#lms-outline-search').fill('');await page.setViewportSize({width:1440,height:900});await page.screenshot({path:process.env.LMS_SCREENSHOT||'/tmp/nextjs-lms-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('[data-lms="outline"]').click();await page.screenshot({path:'/tmp/nextjs-lms-mobile.png'});
assert.deepEqual(errors,[]);console.log('PASS: 390/768/1440px layout, search, all slides, safe Markdown, notes/completion persistence, grading, reports, final gate and independent scrolling');
}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
